### PR TITLE
Moonbeam polkadot v0.9.19

### PR DESCRIPTION
**Pull request by notlesh**
This bumps substrate to `v0.9.19`.

### CODE REVIEW

**Review by girazoki — APPROVED** [review]

**Comment by girazoki** [comment]
actually is the build that fails. Is it because we need to merge https://github.com/PureStake/crowdloan-rewards/pull/56?

**Comment by notlesh** [comment]
It's failing because of:
```
error[E0658]: use of unstable library feature 'proc_macro_is_available'
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.37/src/detection.rs:28:21
   |
28 |     let available = proc_macro::is_available();
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #71436 <https://github.com/rust-lang/rust/issues/71436> for more information
   = help: add `#![feature(proc_macro_is_available)]` to the crate attributes to enable
```

I can confirm (1) `main` is fine, (2) I can reproduce locally. I'll look for a fix...

**Comment by girazoki** [comment]
I just merged your update of the compiler version, maybe try with that

**Comment by notlesh** [comment]
> I just merged your update of the compiler version, maybe try with that

Yeah, bumping `rust-toolchain` helped here.

**Pull request merged**
