### PR TITLE
Store num contributors and intiialized total rewards

### PR DESCRIPTION
**Pull request by girazoki**
This PR adds storage values for the total number of contributors and the initialized reward amount. The first one serves us a potential hint for weight calculation while the latter allows us to be more efficient when closing initialization, where we calculate `total_initialized_reward == Crowdloan funds`

### CODE REVIEW

**Comment by girazoki** [comment]
For a little bit of context, before this PR we were doing DB reads for every contributor that we had already inserted in the system. This means that if we had inserted 500 contributors already, and we were about to insert 100 more, the weight of this 100 more was proportional to 1 DB read per the 500 contributors already in the system. Essentially we went from this:
```

fn initialize_reward_vec(x: u32, y: u32, ) -> Weight {
                (0 as Weight)
                        // Standard Error: 379_000
                        .saturating_add((87_673_000 as Weight).saturating_mul(x as Weight))
                        // Standard Error: 379_000
                        .saturating_add((15_263_000 as Weight).saturating_mul(y as Weight))
                        .saturating_add(T::DbWeight::get().reads(9 as Weight))
                        .saturating_add(T::DbWeight::get().reads((2 as Weight).saturating_mul(x as Weight)))
                        .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(y as Weight)))
                        .saturating_add(T::DbWeight::get().writes(4 as Weight))
                        .saturating_add(T::DbWeight::get().writes((2 as Weight).saturating_mul(x as Weight)))
        }
```
To this

```
fn initialize_reward_vec(x: u32, y: u32, ) -> Weight {
                (0 as Weight)
                        // Standard Error: 161_000
                        .saturating_add((83_692_000 as Weight).saturating_mul(x as Weight))
                        // Standard Error: 161_000
                        .saturating_add((108_000 as Weight).saturating_mul(y as Weight))
                        .saturating_add(T::DbWeight::get().reads(9 as Weight))
                        .saturating_add(T::DbWeight::get().reads((2 as Weight).saturating_mul(x as Weight)))
                        .saturating_add(T::DbWeight::get().writes(7 as Weight))
                        .saturating_add(T::DbWeight::get().writes((2 as Weight).saturating_mul(x as Weight)))
        }

```

**Review by crystalin — APPROVED** [review]
LGTM, I'd like to have someone else review it too

**Review by JoshOrndorff — APPROVED** [review]
This is a good change. Nice work!

If you want to optimize even more, you can leverage the fact that you always read and write these two storage items together. Therefore you could make them into a single storage item (maybe called `CurrentTotals` or something) that stores a pair. That will turn two reads and two writes into one read and one write.

No need to hold this PR up on it though.

**Comment by girazoki** [comment]
Holding the struct merge until we see how total contributors is used with benchmarking

**Pull request merged**
